language: python
python:
  - "2.7"

branches:
  except:
    - master

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.23.zip -nv
  - unzip -q google_appengine_1.9.23.zip
  - export PATH=$PATH:$PWD/google_appengine/

# command to run tests
script: nosetests