language: python
python:
  - "2.7"

branches:
  except:
    - master

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.23.zip -nv
  - unzip google_appengine_1.9.23.zip
  #- export PYTHONPATH=${PYTHONPATH}:google_appengine
  - export PATH=$PATH:$PWD/google_appengine/lib/

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: nosetests