language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - python setup.py build install
# command to run tests
script: nosetest