language: python
python:
  - "2.7"

branches:
  except:
    - master

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.23.zip -nv
  - unzip -q google_appengine_1.9.23.zip
  - export PATH=$PATH:$PWD/google_appengine/

# command to install dependencies
install:
  - pip install -r requirements.txt
   - if [[ ! -f google-cloud-sdk/path.bash.inc ]]; then
      echo "Downloading google cloud sdk";
      wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip;
      unzip -qq google-cloud-sdk.zip;
      google-cloud-sdk/install.sh --usage-reporting false --path-update false --rc-path=~/.bashrc --bash-completion false --override-components=app;
    fi;
  - google-cloud-sdk/bin/gcloud components update preview app --quiet

after_success:
  - ./travis-ci-deploy.sh

# command to run tests
script: nosetests